openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
paths:
  /api/v1/students/basic-information/:
    post:
      summary: "Pre-registro: Información básica"
      tags:
        - Student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BasicInformationStudent"
      responses:
        "201":
          description: El estudiante fue creado exitosamente
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
        "400":
          description: Error de validación en la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: No tienes permisos para realizar esta acción
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "404":
          description: Recurso no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "409":
          description: Conflicto (El estudiante ya existe)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConflictError"
  /api/v1/students/{studentId}/emergency-contact/:
    post:
      summary: "Pre-registro: Contactos de emergencia"
      tags:
        - Student
      parameters:
        - name: studentId
          in: path
          required: true
          description: El id del estudiante
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmergencyContact"
      responses:
        "201":
          description: El estudiante fue creado exitosamente
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
        "400":
          description: Error de validación en la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: No tienes permisos para realizar esta acción
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "404":
          description: Recurso no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "409":
          description: Conflicto (El estudiante ya existe)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConflictError"
  /api/v1/students/{studentId}/family/:
    get:
      summary: "Obtener los familiares"
      tags:
        - Student
      parameters:
        - name: studentId
          in: path
          required: true
          description: El id del estudiante
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: El estudiante fue creado exitosamente
          content:
            application/json:
              schema:
                properties:
                  family:
                    type: array
                    items:
                      $ref: "#/components/schemas/StudentFamily"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: No tienes permisos para realizar esta acción
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "404":
          description: Recurso no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
  /api/v1/students/{studentId}/special-circunstance/:
    post:
      summary: "Pre-registro: Circunstancias especiales"
      tags:
        - Student
      parameters:
        - name: studentId
          in: path
          required: true
          description: El id del estudiante
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpecialCircunstance"
      responses:
        "201":
          description: El estudiante fue creado exitosamente
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
        "400":
          description: Error de validación en la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: No tienes permisos para realizar esta acción
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "404":
          description: Recurso no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "409":
          description: Conflicto (El estudiante ya existe)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConflictError"
  /api/v1/students/circunstances/:
    get:
      summary: "Obtener circunstancias"
      tags:
        - Student
      responses:
        "200":
          description: El estudiante fue creado exitosamente
          content:
            application/json:
              schema:
                properties:
                  circunstances:
                    type: array
                    items:
                      $ref: "./components.schemas.yaml#/components/schemas/Circunstance"
                    example:
                      - id: "550e8400-e29b-41d4-a716-446655440000"
                        name: "Mudanzas"
                        isActive: true
                        createdAt: "2021-10-10T00:00:00.000Z"
                        updatedAt: "2021-10-10T00:00:00.000Z"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: No tienes permisos para realizar esta acción
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "404":
          description: Recurso no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
components:
  schemas:
    BasicInformationStudent:
      type: object
      description: Esquema para iniciar el preregistro
      properties:
        branchId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000" 
        name:
          type: string
          example: Edwin
        paternalSurname:
          type: string
          example: Garcia
        maternalSurname:
          type: string
          example: Quiterio
        gender:
          type: string
          enum: [m, f]
          example: m
        entryTime:
          type: string
          format: time
          example: "07:00"
        exitTime:
          type: string
          format: time
          example: "13:00"
        brothersNumber:
          type: integer
          example: 3
        allergyDescription:
          type: string
          example: Al trabajo
        familyStatus:
          type: string
          enum: [Viven juntos, Separados, Viudo(a), Padre o madre soltero(a)]
          example: Viven juntos
    EmergencyContact:
      type: object
      description: Esquema Para los contactos de emergencia
      properties:
        studentId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        studentFamilyId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000" 
        priorityLevel:
          type: string
          enum: [primary, secondary]
          example: primary
      required:
        - studentId
        - studentFamilyId
        - priorityLevel
    SpecialCircunstance:
      type: object
      description: Esquema Para los circunstancias especiales
      properties:
        studentId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        circunstanceId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000" 
        other:
          type: string
          example: "Se cayó y se pego en la moyera"
      required:
        - studentId
        - circunstanceId
    Circunstance:
      type: object
      description: Esquema Para los contactos de emergencia
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000" 
        name:
          type: string
          example: "Mudanzas"
        isActive:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: "2021-10-10T00:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2021-10-10T00:00:00.000Z"
    StudentFamily:
      type: object
      description: Esquema Para los contactos de emergencia
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000" 
        familiers:
          type: array
          items:
            properties:
              id:
                type: string
                format: uuid
                example: "550e8400-e29b-41d4-a716-446655440000"
              relationship:
                $ref: "#/components/schemas/RelationshipResponse"
              person:
                $ref: "#/components/schemas/PersonResponse"
                  
    
    PersonResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        branchId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000" 
        name:
          type: string
          example: José
        paternalSurname:
          type: string
          example: Garcia
        maternalSurname:
          type: string
          example: Quiñones
        birthday:
          type: string
          format: date
          example: "1990-10-10"
        phoneNumber:
          type: string
        gender:
          type: string
          enum: [m, f]
          example: m
        isActive:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: "2021-10-10T00:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2021-10-10T00:00:00.000Z"
    RelationshipResponse: 
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        name: 
          type: string
          example: "Papá"
        description:
          type: string
          example: "Padre del estudiante"
        isActive:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: "2021-10-10T00:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2021-10-10T00:00:00.000Z"
    StudentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        person:
          $ref: "#/components/schemas/PersonResponse"

# Schemas generales para todos los endpoints
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "El campo 'name' es obligatorio"

    UnauthorizedError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 401
        error:
          example: "Unauthorized"
        message:
          example: "No tienes permisos para acceder a este recurso"

    ForbiddenError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 403
        error:
          example: "Forbidden"
        message:
          example: "No tienes autorización para realizar esta acción"

    NotFoundError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 404
        error:
          example: "Not Found"
        message:
          example: "Recurso no encontrado"

    ConflictError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 409
        error:
          example: "Conflict"
        message:
          example: "El estudiante ya está registrado"

    InternalServerError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 500
        error:
          example: "Internal Server Error"
        message:
          example: "Ocurrió un error inesperado en el servidor"
