openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
paths:
  /students/basic-information/:
    post:
      summary: "Pre-registro: Información básica"
      tags:
        - Student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BasicInformationStudent"
      responses:
        "201":
          description: El estudiante fue creado exitosamente
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
        "400":
          description: Error de validación en la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: No tienes permisos para realizar esta acción
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "404":
          description: Recurso no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "409":
          description: Conflicto (El estudiante ya existe)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConflictError"
  /students/{studentId}/emergency-contact/:
    post:
      summary: "Pre-registro: Información básica"
      tags:
        - Student
      parameters:
        - name: studentId
          in: path
          required: true
          description: El id del estudiante
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmergencyContact"
      responses:
        "201":
          description: El estudiante fue creado exitosamente
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
        "400":
          description: Error de validación en la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: No autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: No tienes permisos para realizar esta acción
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "404":
          description: Recurso no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "409":
          description: Conflicto (El estudiante ya existe)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConflictError"
           
components:
  schemas:
    BasicInformationStudent:
      type: object
      description: Esquema para iniciar el preregistro
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        branchId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        parentFamilyId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000" 
        name:
          type: string
          example: Edwin
        paternalSurname:
          type: string
          example: Garcia
        maternalSurname:
          type: string
          example: Quiterio
        gender:
          type: string
          enum: [m, f]
          example: m
        entryTime:
          type: string
          format: time
          example: "07:00"
        exitTime:
          type: string
          format: time
          example: "13:00"
        brothersNumber:
          type: integer
          example: 3
        allergyDescription:
          type: string
          example: Al trabajo
        familyStatus:
          type: string
          enum: [Viven juntos, Separados, Viudo(a), Padre o madre soltero(a)]
          example: Viven juntos
    EmergencyContact:
      type: object
      description: Esquema Para los contactos de emergencia
      properties:
        studentId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        parentFamilyId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000" 
        priorityLevel:
          type: string
          enum: [primary, secondary]
          example: primary
        


# Schemas generales para todos los endpoints
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "El campo 'name' es obligatorio"

    UnauthorizedError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 401
        error:
          example: "Unauthorized"
        message:
          example: "No tienes permisos para acceder a este recurso"

    ForbiddenError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 403
        error:
          example: "Forbidden"
        message:
          example: "No tienes autorización para realizar esta acción"

    NotFoundError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 404
        error:
          example: "Not Found"
        message:
          example: "Recurso no encontrado"

    ConflictError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 409
        error:
          example: "Conflict"
        message:
          example: "El estudiante ya está registrado"

    InternalServerError:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
      properties:
        statusCode:
          example: 500
        error:
          example: "Internal Server Error"
        message:
          example: "Ocurrió un error inesperado en el servidor"
